@startuml
!pragma layout smetana

package measurement {
    class Measurement <<Entity>> <<Root>> {
    }
    class LogID <<ValueObject>> <<ID>> {
        - _id : String
    }
    class DeviceID <<ValueObject>> <<ID>> {
        - _id : String
    }
    class SensorID <<ValueObject>> <<ID>> {
        - _id : String
    }
    class TimeStamp <<ValueObject>> {
        - _timestamp : LocalDateTime
    }
    class SensorValue <<ValueObject>>{
        - _value : anyPrimitive
    }
    class TypeDescription <<ValueObject>> {
        - _description : String
    }
    class Unit <<ValueObject>> {
        - _unit : String
    }

}

Measurement "1" -- "1" TimeStamp : has
Measurement "1" -- "1" DeviceID : has
Measurement "1" -- "1" SensorID : has
Measurement "1" -- "1" SensorValue : has
Measurement "1" -- "1" LogID : has
Measurement "1" -- "1" TypeDescription : has
Measurement "1" -- "1" Unit : has


@enduml