@startuml
!pragma layout smetana

package SmartHome.SensorModel{

    class SensorModel <<Entity>> <<Root>>{
    - _sensorModelName : SensorModelName
    - _modelPath : SensorModelPath
    }
}

package SmartHome.SensorModel {
     class SensorModelPath <<ValueObject>><<ID>>{
        - _path : String
     }
     class SensorModelName <<ValueObject>>{
        - _sensorModelName : String
     }
}

SmartHome.SensorModel.SensorModel "1" -- "1" SmartHome.SensorModel.SensorModelPath : has
SmartHome.SensorModel.SensorModel "1" -- "1" SmartHome.SensorModel.SensorModelName : has
@enduml