@startuml
'https://plantuml.com/class-diagram
!pragma layout smetana

package sensor {
    class Sensor <<Entity>> <<Root>> {
        - _deviceID : DeviceID
        - _sensorTypeDescription : SensorTypeDescription
        - _modelPath : ModelPath
        - _sensorName : SensorName
        - _value : Value
    }
    class DeviceID <<ValueObject>> <<ID>> {
        - _id : String
    }

    class SensorTypeDescription <<ValueObject>> <<ID>> {
        - _id : String
    }
    class SensorModelPath <<ValueObject>> <<ID>> {
        - _id : String
    }

    class SensorName <<ValueObject>> {
        - _name : String
    }

    class ValueImpl <<ValueObject>>{
    }

    class SensorID <<ValueObject>> <<ID>> {
        - _id : String
    }
}

Sensor "*" -- "1" SensorTypeDescription : has
Sensor "*" -- "1" SensorModelPath : has
Sensor "1" -- "1" ValueImpl : has
Sensor "*" -- "1" DeviceID : has
Sensor "*" -- "1" SensorName : has
Sensor "1" -- "1" SensorID : has

@enduml