@startuml
'https://plantuml.com/sequence-diagram
!pragma layout smetana

autonumber

actor "User" as User
participant "RestClient" as RC

box "SmartHome"
    participant "Server" as SV
    participant "DataBase" as BD
end box

User -> RC :  I want to get a list of all actuators in a device
activate RC

RC -> SV : getActuatorsByDeviceID (deviceID)
activate SV

SV -> BD : getActuatorsByDeviceID (deviceID)
activate BD

BD --> SV : listActuatorDataModel
deactivate BD

SV --> RC : listActuatorsDTO
deactivate SV

RC --> User : listActuatorsDTO
deactivate RC


@enduml