@startuml
!pragma layout smetana

package SmartHome.ActuatorModel{

    class ActuatorModel <<Entity>> <<Root>>{
    - _actuatorTypeID : ActuatorTypeID
    - _actuatorModelName : ActuatorModelName
    - _modelPath: ModelPath
    }
}

package SmartHome.ValueObject {

     class ActuatorTypeId <<ValueObject>>{
        - _actuatorTypeId : String
     }

     class ModelPath <<ValueObject>>{
        - _modelPath : String
     }
     class ActuatorModelName <<ValueObject>>{
        - _actuatorModelName : String
     }
}

SmartHome.ActuatorModel.ActuatorModel "1" -- "1" SmartHome.ValueObject.ActuatorTypeId : has
SmartHome.ActuatorModel.ActuatorModel "1" -- "1" SmartHome.ValueObject.ModelPath : has
SmartHome.ActuatorModel.ActuatorModel "1" -- "1" SmartHome.ValueObject.ActuatorModelName : has


@enduml