@startuml
'https://plantuml.com/class-diagram
!pragma layout smetana

package SmartHome.AggregateActuator {
    class Actuator <<Entity>> <<Root>> {
        - _deviceID : DeviceID
        - _actuatorTypeID : ActuatorTypeID
        - _actuatorModelID : ActuatorModelID
        - _value : Value
    }
}

package SmartHome.ValueObject {
    class DeviceID <<ValueObject>> <<ID>> {
        - _id : String
    }

    class ActuatorTypeID <<ValueObject>> <<ID>> {
        - _id : String
    }
    class ActuatorModelID <<ValueObject>> <<ID>> {
        - _id : String
    }

    interface Value <<ValueObject>>{
    }
}

Actuator "*" -- "1" ActuatorTypeID : has
Actuator "*" -- "1" ActuatorModelID : has
Actuator "1" -- "1" Value : has
Actuator "*" -- "1" DeviceID : has


@enduml