@startuml
!pragma layout smetana

package SmartHome.SensorType {

  class SensorType<<Entity>><<Root>> {
    - _sensorTypeDescription : SensorTypeDescription
    - _measurementUnit : MeasurementUnit
  }

}
package SmartHome.SensorType {
  class SensorTypeDescription<<Value Object>><<ID>> {
    - _description: String
  }
  class MeasurementUnit<<Value Object>><<ID>> {
      - _unit: String
    }

}
SmartHome.SensorType.SensorType "1" -- "1" MeasurementUnit
SmartHome.SensorType.SensorType "1" -- "1" SensorTypeDescription


@enduml
