@startuml
!pragma layout smetana

package SmartHome.Unit {
    class Unit <<Entity>><<Root>> {
        - _id: UnitID
        - _symbol: Symbol
        - _description: UnitDescription

    }
    class UnitDescription <<ValueObject>> {
        - _unit: string
        }
    class Symbol<<ValueObject>> {
        - _symbol: string
        }
     class UnitID <<ValueObject>><<ID>> {
        - _id: string
        }

Unit "1  " --> "1" UnitDescription
Unit "1" --> "1  " Symbol
Unit "1" --> "1  " UnitID
}
@enduml