@startuml
!pragma layout smetana
autonumber

actor "  " as User
participant ":AddSensorTypeController" as Controller
participant ":SensorTypeService" as Service
participant ":Unit" as Unit
participant ":SensorTypeFactory" as Factory
participant "sensorType:SensorType" as Type
participant ":SensorTypeRepository" as Repository
participant ":SensorTypeAssembler" as Assembler
participant "sensorTypeDTO:SensorTypeDTO" as DTO

User o-> Controller: createSensorType()
activate Controller
Controller -> Service: getAllSupportedUnits()
activate Service
Service -> Unit: getAll()
activate Unit
Unit --> Service: units
deactivate Unit
Service --> Controller: units
deactivate Service
Controller --> User: units
deactivate Controller
User o-> Controller: createSensorType(String name, String units)

'------------------------------------------------------------------'
activate Controller
Controller -> Service: createSensorType(String name, String units)
activate Service
Service -> Factory: addSensorType(String name, Unit unit)
activate Factory
create Type
Factory -> Type: createSensorType(String name, Unit unit)
activate Type
Type --> Factory: sensorType
deactivate Type
Factory --> Service: sensorType
deactivate Factory
Service -> Repository: save(sensorType)
activate Repository
Repository -> Service: sensorType
deactivate Repository
Service -> Assembler: domainToDTO(sensorType)
activate Assembler
create DTO
Assembler -> DTO: domainToDTO(sensorType)
activate DTO
DTO --> Assembler: sensorTypeDTO
deactivate DTO
Assembler --> Service: sensorTypeDTO
deactivate Assembler
Service --> Controller: sensorTypeDTO
deactivate Service
Controller --> User: sensorTypeDTO
deactivate Controller

@enduml