@startuml
'https://plantuml.com/sequence-diagram

actor "User" as User
participant RestClient as "RestClient"
box "Power Consumption"
participant Controller as "Controller"
participant Service as "Service"
participant Repository as "Repository"
participant Domain as "Domain"
participant DataBase as "DataBase"
end box

autonumber

User -> RestClient :  want to get the maximum instantaneous temperature difference between a device in the room and the outside

activate RestClient

RestClient -> Controller: getMaxInstTempDiffBetweenDeviceAndOutside (outsideDeviceDTO, insideDeviceDTO, initialTime, endTime, timeDelta)

activate Controller

Controller -> Domain :DeviceID(outsideDeviceIDStr)
activate Domain
Domain --> Controller : deviceID
deactivate Domain

Controller -> Domain: DeviceID(insideDeviceIDStr)
activate Domain
Domain --> Controller : deviceID
deactivate Domain

Controller -> Domain: SensorType(strTemperature)
activate Domain
Domain --> Controller : sensorType
deactivate Domain

Controller -> Domain: DatePeriod(initialTime, endTime)
activate Domain
Domain --> Controller : datePeriod
deactivate Domain

Controller -> Domain: TimeDelta(intTimeDelta)
activate Domain
Domain --> Controller : timeDelta
deactivate Domain

Controller -> Service: getMaxInstTempDiffBetweenDeviceAndOutside(insideDeviceID, sensorType, timeDelta)
activate Service
Service -> Repository: findByDeviceIDAndSensorTypeAndDatePeriodBetween(deviceID, sensorTypeID, period)

activate Repository
Repository -> DataBase: find
activate DataBase
DataBase --> Repository: List<Log>
deactivate DataBase

Repository --> Service: ListLogInsideReadings
deactivate Repository

Service --> Controller: ListLogInsideReadings
deactivate Service

Controller -> Service: getMaxInstTempDiffBetweenDeviceAndOutside(outsideDeviceID, sensorType, timeDelta)
activate Service
Service -> Repository: findByDeviceIDAndSensorTypeAndDatePeriodBetween(deviceID, sensorTypeID, period)

activate Repository
Repository -> DataBase: find
activate DataBase
DataBase --> Repository: List<Log>
deactivate DataBase



Repository --> Service: listLogsOutsideReadings
deactivate Repository

Service --> Controller: listLogsOutsideReadings
deactivate Service

Controller -> Service: getMaxInstTempDiffBetweenDeviceAndOutside(insideReadings, outsideReadings, timeDelta)
activate Service

Service --> Controller: maxInstTempDiff
deactivate Service

Controller --> RestClient: maxInstTempDiff
deactivate Controller

RestClient --> User: maxInstTempDiff
deactivate RestClient






@enduml