@startuml
'https://plantuml.com/sequence-diagram
!pragma layout smetana

autonumber

actor "User" as User
participant "RestClient" as RC

box "SmartHome"
    participant "Controller" as CTRL
    participant "Service" as SV
    participant "Repository" as REPO
    participant "Domain" as DOM
    participant "DataBase" as BD
end box

User o-> RC : I want to add an actuator to a device
activate RC
RC -> CTRL : addActuatorToDevice(actuatorDataDTO)
activate CTRL
CTRL -> DOM : CreateDeviceID(actuatorDataDTO)
activate DOM
DOM -> CTRL : deviceID
deactivate DOM
CTRL -> DOM : CreateModelPath(actuatorDataDTO)
activate DOM
DOM -> CTRL : modelPath
deactivate DOM
CTRL -> DOM : CreateActuatorTypeID(actuatorDataDTO)
activate DOM
DOM -> CTRL : actuatorTypeID
deactivate DOM
CTRL -> DOM : CreateActuatorName(actuatorDataDTO)
activate DOM
DOM -> CTRL : actuatorName
deactivate DOM

CTRL -> SV : addActuatorToDevice(addActuatorToDevice(ActuatorModelID, deviceID, ActuatorTypeID, ActuatorName)
activate SV
SV -> REPO : save(actuator)
activate REPO
REPO -> BD : save(actuator)
REPO --> SV : actuator
deactivate REPO

SV -> CTRL : actuator
deactivate SV
CTRL -> RC : actuator
deactivate CTRL
RC -> User : actuatorDTO
deactivate RC


@enduml