@startuml
'https://plantuml.com/use-case-diagram
'left to right direction
skinparam actorStyle awesome
skinparam ActorBackgroundColor black

:Administrator: as Admin
:Power User: as Power_User
:Room Owner: as Room_Owner

(US03/UC03: To get list of rooms) as (Use3)
(US06/UC06: To get list of devices in a room) as (Use6)

Admin -left-> (Use6)

Power_User -right-> (Use6)

Room_Owner -down-> (Use6)

(Use6) ..> (Use3): <<includes>>

@enduml