@startuml
'https://plantuml.com/use-case-diagram

!pragma layout smetana
skinparam actorStyle awesome
skinparam ActorBackgroundColor black

actor Administrator as Admin
actor "Power User" as Power_User


    (Deactivate Device) as UC1
    (Request All Devices) as UC2
    UC1 --> UC2 : <<includes>>


Admin -left-> UC1
Power_User -right-> UC1


@enduml

