@startuml
'https://plantuml.com/class-diagram
!pragma layout smetana

class GetAllDevicesGroupedByFunctionalityController {
    -_deviceService: DeviceService
    -_deviceAssembler: DeviceAssembler

    +GetAllDevicesGroupedByFunctionalityController(deviceService: DeviceService)
    +getAllDevicesGroupedByFunctionality(): Map<String, List<DeviceDTO>>

}

class DeviceService {
    -_deviceFactory: DeviceFactory
    -_deviceRepo: DeviceRepository
    +DeviceService(factoryDevice: FactoryDevice, deviceRepo: DeviceRepository)
    +getDevices(): List<DeviceDTO>
}

class DeviceRepository {
    -_data: HashMap<DeviceID, Device>
    +DeviceRepository()
    +findAll(): List<Device>
}

class DeviceAssembler {
    +DeviceAssembler()
    +device2DTO(devices: List<Device>): List<DeviceDTO>
}

class DeviceDTO {
    +id: String
    +roomID: String
    +name: String
    +deviceType: String
    +DeviceDTO(id: DeviceID, roomID: RoomID, name: DeviceName, deviceType: DeviceType)
}

GetAllDevicesGroupedByFunctionalityController "1" ..> "1" DeviceService: uses
DeviceService "1" ..> "1" DeviceRepository: uses
GetAllDevicesGroupedByFunctionalityController "1" ..> "1" DeviceAssembler: uses
DeviceAssembler "1" ..> "*" DeviceDTO: creates
@enduml