@startuml
'https://plantuml.com/component-diagram
component SmartHome <<system (C4)>> {

    port p1

    component Frontend {
        port p2
        port p3
        port p4
    }

    component Backend {
            port p5
        }

    component WeatherService {

            port p6
        }
}

p1 -up- UI
p1 - p2
p3 -(0- p5
p4 -(0- p6


@enduml