@startuml
!pragma layout smetana

package SmartHome.sensors {

  class SolarIrradianceSensor {
    - _sensorType: SensorType
    - _value: SetIrradianceSensor
    + SolarIrradianceSensor(CatalogueSensor catalogue)
    - setSensorType(CatalogueSensor catalogue) : void
    + getSensorType(): ActuatorType
    + getValue(): Value

  }

  class SolarIrradianceValue {
    - _value : int
    + SolarIrradianceValue(int value)
    + toString() : String
  }

}

package SmartHome.domain {

  interface Sensor {
        + getSensorType(): SensorType
        + getValue(): Value
  }

  interface Value {
  }

  class SensorType {
    - _description: String
    - _unit: Unit
    # SensorType(String strDescription, Unit unit)
    - setStrDescription(String strDescription) : void
    - setUnit(Unit unit) : void
    + getDescription() : String
    + getUnit() : Unit
  }

 class CatalogueSensor {
    - _listSensorTypes: List<SensorType>
    - _listStringClassesSensor : List<String>
    + CatalogueSensor(String filePathname)
    - setListSensorTypes() : void
    - setListStringClassesSensors() : void
    + addSensorType(String strDescription, Unit unit, SensorTypeFactory sensorTypeFactory) : SensorType
    + addSensorTypeToList(SensorType sensorType): SensorType
    + getSensorType(String strDescription): SensorType
    + getSensorTypes(): List<SensorType>
    + getSensorModels(): List<String>
    + getSensor(String strModel, SensorFactory sensorFactory): Sensor
 }


}

SmartHome.sensors.SolarIrradianceSensor "1" ..|>  "1" SmartHome.domain.Sensor : <<implements>>
SmartHome.sensors.SolarIrradianceSensor --> SmartHome.domain.SensorType : <<has>>
SmartHome.sensors.SolarIrradianceSensor --> SmartHome.sensors.SolarIrradianceValue : <<has>>
SmartHome.sensors.SolarIrradianceValue ..|> SmartHome.domain.Value : <<implements>>
SmartHome.sensors.SolarIrradianceSensor ..> SmartHome.domain.CatalogueSensor : <<uses>>

@enduml
