@startuml
'https://plantuml.com/component-diagram
component SmartHome <<system (C4)>> {
    port p1
    port p2

    component Backend {
        port p3
        port p4
        component Database
        component Server
    }

    component CLI{
        port p5
        port p6
    }
}

CLIUI -down- p1
p5 - p1
p6 -(0- p4

p3 - p2
p2 -up- APIRest

Database -(0- Server

@enduml