@startuml
'https://plantuml.com/component-diagram
component Backend <<system (C4)>> {

    port p1

    component Server {
        port p2
        port p3
    }

    component DataBase {
            port p4
        }
}

p1 -up- API
p1 - p2

p3 -(0- p4


@enduml