@startuml
participant "  " as User
participant ":ControlerX" as Controller
participant ":ServiceX" as Service
participant ":FactoryX" as Factory
participant "entity:EntityX" as Entity
participant ":RepositoryX" as Repository



User -> Controller: 1: createEntityAndAddToRepo(EntityDTO entityData)
Controller -> Controller: DTOtoDomain(): valueObject
Controller -> Service: 1.1: createEntityAndAddToRepo(valueObject, ...)
activate Service

Service -> Factory: 1.1.2: CreateEntity(valueObject, ...)
activate Factory

create Entity
Factory -> Entity: 1.1.2.1: createEntity(String name, String units)
activate Entity
Entity --> Factory: entity
deactivate Entity
Factory --> Service: entity
deactivate Factory
activate Repository
Service --> Repository: 1.1.3: addToRepository(entity)
Repository --> Service: entity
deactivate Repository
Service --> Controller: entity



deactivate Service
deactivate Assembler
Controller --> User: entityDTO

@enduml