@startuml
participant "  " as User
participant ":ControlerX" as Controller
participant ":ServiceX" as Service
participant ":RepositoryX" as Repository
participant ":AssemblerX" as Assembler
participant "entityDTO:XDTO" as DTO


User -> Controller: 1: getAllEntity's()
Controller -> Service: 1.1: getAllEntity's(): ListEntityDTO
activate Service
Service -> Repository: 1.1.1: getAllEntity's()
activate Repository
Repository --> Service: listEntity
deactivate Repository
Service -> Assembler: 1.1.2: domainToDTO(listEntity)
activate Assembler
create DTO
loop
Assembler -> DTO: 1.1.2.1: domainToDTO(listEntity): ListEntityDTO
activate DTO
DTO --> Assembler: entityDTO
Assembler -> Assembler: addToList(entityDTO)
deactivate DTO
end
Assembler --> Service: listEntityDTO
deactivate Assembler
Service --> Controller: listEntityDTO
deactivate Service
Controller --> User: listEntityDTO

@enduml