@startuml
'https://plantuml.com/sequence-diagram

actor "User" as User
participant RestClient as "RestClient"
box "Power Consumption"
participant Controller as "Controller"
participant Service as "Service"
participant Repository as "Repository"
participant DataBase as "DataBase"
end box

autonumber

User -> RestClient :  I want to get the peak power consumption of the house, in a given period
activate RestClient

RestClient -> Controller: getMaxPowerConsumption(initialTime, endTime)

activate Controller

Controller -> Service: getDevicesByDeviceTypeID(powerMeterTypeID)

activate Service

Service -> Repository: getDevicesByDeviceTypeID(powerMeterTypeID)

activate Repository

Repository -> DataBase: findByDeviceTypeID

activate DataBase

DataBase --> Repository : deviceList

deactivate DataBase

Repository --> Service: deviceList

deactivate Repository

Service -> Controller: deviceList

deactivate Service

'--------------------------------------------'

Controller -> Service: getDevicesByDeviceType(powerSourceTypeID)

activate Service

Service -> Repository: getDevicesByDeviceType(powerSourceTypeID)

activate Repository

Repository -> DataBase: findByDeviceTypeID

activate DataBase

DataBase --> Repository : deviceList

deactivate DataBase

Repository --> Service: deviceList

deactivate Repository

Service -> Controller: deviceList

deactivate Service

'--------------------------------------------'

Controller -> Service: getDeviceReadingsBySensorTypeAndTimePeriod (powerMeterDeviceID, sensorTypeID, datePeriod)

activate Service

Service -> Repository: findByDeviceIDAndSensorTypeAndDatePeriodBetween (powerMeterDeviceID, sensorTypeID, datePeriod)

activate Repository

Repository -> DataBase: findByDeviceTypeID

activate DataBase

DataBase --> Repository : readingsList

deactivate DataBase

Repository --> Service: powerMeterReadings

deactivate Repository

Service --> Controller: powerMeterReadings

deactivate Service

Controller -> Service: getDeviceReadingsBySensorTypeAndTimePeriod (powerSourceDeviceID, sensorTypeID, datePeriod)

'--------------------------------------------'

activate Service

Service -> Repository: findByDeviceIDAndSensorTypeAndDatePeriodBetween (powerSourceDeviceID, sensorTypeID, datePeriod)

activate Repository

Repository -> DataBase: findByDeviceIDAndSensorTypeAndDatePeriodBetween

activate DataBase

DataBase --> Repository : readingsList

deactivate DataBase

Repository --> Service: powerSourceReadings

deactivate Repository

Service --> Controller: powerSourceReadings

deactivate Service

Controller -> Service: getMaxPowerConsumption(powerMeterReadings, powerSourceReadings, timeDelta)

'--------------------------------------------'

activate Service

Service --> Controller: maxPowerConsumptionValue

deactivate Service

Controller --> RestClient: maxPowerConsumptionValue

deactivate Controller

RestClient --> User: maxPowerConsumptionValue

deactivate RestClient

@enduml