@startuml
'https://plantuml.com/sequence-diagram
!pragma layout smetana

autonumber

actor "User" as User
participant "RestClient" as RC

box "SmartHome"
    participant "Controller" as CTRL
    participant "Service" as SV
    participant "Repository" as REPO
    participant "Domain" as DOM
    participant "DataBase" as BD
end box


User -> RC : I want to get all devices grouped by functionality
activate RC


RC -> CTRL: getAllDevicesGroupedByFunctionality()
activate CTRL


CTRL -> SV: getAllDevices()
activate SV

SV -> REPO : findAll()
activate REPO

REPO -> BD : find

REPO --> SV : deviceTypeList
deactivate BD

SV --> CTRL : deviceTypeList

deactivate REPO

CTRL -> SV : getDevicesByDeviceTypeID(deviceTypeID)

SV -> REPO : findByDeviceTypeID(deviceTypeID)
activate REPO

REPO -> BD : find

REPO --> SV : deviceList
deactivate REPO

SV --> CTRL : deviceList
deactivate SV

CTRL --> RC : map <deviceTypeDTO, List<deviceDTOList>>
deactivate CTRL

RC --> User : map <deviceTypeDTO, List<deviceDTOList>>
deactivate RC


@enduml