@startuml
'https://plantuml.com/sequence-diagram
!pragma layout smetana
autonumber

actor "User" as User
participant RestClient as "RestClient"
box "SmartHome"
participant Controller as "Controller"
participant Service as "Service"
participant Repository as "Repository"
participant Domain as "Domain"
participant DataBase as "DataBase"
end box

User o-> RestClient: getActuatorsByDeviceID(strDeviceID)
activate RestClient

RestClient -> Controller: getActuatorsByDeviceID(strDeviceID)
activate Controller

Controller -> Domain: DeviceID(strDeviceID)
activate Domain

Domain --> Controller: deviceID
deactivate Domain

Controller -> Service : getActuatorsByDeviceID(deviceID)
activate Service

Service -> Repository: ofDeviceID(deviceID)
activate Repository

Repository -> DataBase: findByDeviceID
activate DataBase

DataBase --> Repository: listActuatorsDataModel
deactivate DataBase

Repository --> Service: listActuators
deactivate Repository

Service --> Controller: listActuators
deactivate Service

Controller --> RestClient: actuatorListDTO
deactivate Controller

RestClient --> User: actuatorListDTO
deactivate RestClient



@enduml