@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "Administrator/Power User" as admin

admin -> System: I want to deactivate a device
System -> admin: What device do you want to deactivate?
admin -> System: I want to deactivate this device
System -> admin: Device deactivated


@enduml