@startuml

participant " " as User
participant ":ConfigureHouseLocation" as Controller
participant ":LocationAssembler" as Assembler
participant "locationDTO:LocationDTO" as LocationDTO
participant ":House" as House
participant ":LocationFactory" as LocationFactory
participant "location:Location" as Location
participant ":AddressFactory" as AddressFactory
participant "address:Address" as Address
participant ":GpsFactory" as GpsFactory
participant "gps:GPS" as GPS

autonumber
User o-> Controller: configureLocation(street ,zipCode, doorNumber, latitude, longitude)
activate Controller

Controller -> House : configureLocation (street ,zipCode, doorNumber, latitude, longitude)
activate House
create LocationFactory

House -> LocationFactory: configureLocation(street,zipCode, doorNumber, latitude, longitude)
deactivate House
activate LocationFactory

create Location
LocationFactory -> Location: createLocation(street, zipCode, doorNumber, latitude, longitude)
activate Location

create AddressFactory
Location -> AddressFactory: setAdress(street, zipCode, doorNumber)
activate AddressFactory
create Address
AddressFactory -> Address: createAddress(street, zipCode, doorNumber)
activate Address
Address --> AddressFactory: address
deactivate Address
AddressFactory --> Location : address
deactivate AddressFactory



create GpsFactory
Location -> GpsFactory: setGpsLocation(latitude, longitude)
activate GpsFactory
create GPS
GpsFactory-> GPS : createGPS (latitude, longitude)
activate GPS
GPS --> GpsFactory: gps
GpsFactory --> Location : gps
deactivate GpsFactory
deactivate GPS

Location --> LocationFactory: location
deactivate Location
LocationFactory --> House: location
deactivate LocationFactory
House --> Controller: location

create Assembler
Controller -> Assembler: createLocationDTO(location)
activate Assembler
create LocationDTO
Assembler -> LocationDTO: domainToDTO(location)
activate LocationDTO
LocationDTO --> Assembler: locationDTO
deactivate LocationDTO

Assembler --> Controller: locationDTO
deactivate Assembler
Controller --> User: locationDTO
deactivate Controller
@enduml