@startuml
'https://plantuml.com/sequence-diagram
!pragma layout smetana

participant " " as User

box "Controller" #LightBlue
participant ":GetListOfRooms_Controller" as GetListOfRoomsController
end box

box "Service" #LightGreen
participant "serviceRoom:ServiceRoom" as Service
end box

box "Repository" #LightYellow
participant "RepoRoom:RepositoryRoom" as RepositoryRoom
end box

box "Assembler" #LightCyan

participant ":RoomAssembler" as RoomAssembler

participant "roomDTO:RoomDTO" as RoomDTO

end box
autonumber

User o-> GetListOfRoomsController: getRooms()

activate GetListOfRoomsController

GetListOfRoomsController -> Service: getRooms()

activate Service

Service -> RepositoryRoom: findAll()

activate RepositoryRoom

RepositoryRoom --> Service: listOfRooms

deactivate RepositoryRoom

Service -> RoomAssembler: domain2DTO(listOfRooms)

loop  for each room in Rooms
create RoomDTO
activate RoomAssembler
RoomAssembler -> RoomDTO: createRoomDTO(room)
activate RoomDTO
RoomDTO --> RoomAssembler: roomDTO
deactivate RoomDTO
RoomAssembler -> RoomAssembler : addRoomDTO2List (roomDTO)
end

RoomAssembler --> Service: roomDTOList
deactivate RoomAssembler



Service --> GetListOfRoomsController: roomsDTOList

deactivate Service

<-- GetListOfRoomsController :roomsDTOList

deactivate GetListOfRoomsController


@enduml