@startuml
'https://plantuml.com/sequence-diagram
!pragma layout smetana

participant " " as User

box "Controller" #LightBlue
participant ":GetListOfRooms_Controller" as GetListOfRooms_Controller
end box

box "Service" #LightGreen
participant "ServiceRoom" as Service
end box

box "Repository" #LightYellow
participant "RepoRoom:RepositoryRoom" as RepositoryRoom
end box

box "Assembler" #LightCyan

participant ":RoomAssembler" as RoomAssembler

participant "roomDTO:RoomDTO" as RoomDTO

end box
autonumber

User o-> GetListOfRooms_Controller: getRooms()

activate GetListOfRooms_Controller

GetListOfRooms_Controller -> Service: getRooms()

activate Service

Service -> RepositoryRoom: findAll()

activate RepositoryRoom

RepositoryRoom --> Service: listOfRooms

deactivate RepositoryRoom


loop  for each room in Rooms

Service -> RoomAssembler: domain2DTO(room)
create RoomDTO
activate RoomAssembler
RoomAssembler -> RoomDTO: createRoomDTO(room)
activate RoomDTO
RoomDTO --> RoomAssembler: roomDTO
deactivate RoomDTO
RoomAssembler --> Service: roomDTO
deactivate RoomAssembler
Service -> Service: saveRoomDTO(roomDTO)

end

Service --> GetListOfRooms_Controller: roomsDTOs

deactivate Service

<-- GetListOfRooms_Controller :listOfRoomsDTOs

deactivate GetListOfRooms_Controller


@enduml