@startuml
participant "  " as User
participant ":AddSensorTypeController" as Controller
participant "Unit" as Unit
participant ":SensorTypeService" as Service
participant ":SensorTypeFactory" as SensorTypeFactory
participant "sensortype:SensorType" as SensorType
participant "SensorTypeAssembler" as SensorTypeAssembler
participant "sensorTypeDTO:SensorTypeDTO" as SensorTypeDTO

User o-> Controller: 1: createSensorType()
activate Controller
Controller -> Unit: 1.1: getAllSupportedUnits()
activate Unit
Unit --> Controller: 1.2: units
deactivate Unit
Controller --> User: 1.3: units
User -> Controller: 2: createSensorType(String name, String units)
Controller -> Service: 2.1: createSensorType(String name, String units)
activate Service
activate SensorTypeFactory
Service -> SensorTypeFactory: 2.1.1: addSensorType(String name, String units)
create SensorType
SensorTypeFactory -> SensorType: 2.1.2: createSensorType(String name, String units)
activate SensorType
SensorType --> SensorTypeFactory: 2.1.3: sensorType
deactivate SensorType
SensorTypeFactory --> Service: 2.1.4: sensorType
deactivate SensorTypeFactory
Service -> SensorTypeAssembler: 2.2: domainToDTO(sensorType)

activate SensorTypeAssembler
create SensorTypeDTO
SensorTypeAssembler -> SensorTypeDTO: 2.2.1: domainToDTO(sensorType)
activate SensorTypeDTO
SensorTypeDTO --> SensorTypeAssembler: 2.2.2: sensorTypeDTO
deactivate SensorTypeDTO
SensorTypeAssembler --> Service: 2.2.3: sensorTypeDTO
Service --> Controller: 2.2.4: sensorTypeDTO
deactivate Service
deactivate SensorTypeAssembler
Controller --> User: 2.2.5: sensorTypeDTO

@enduml