@startuml
!pragma layout smetana

participant User as User
participant ":AddDeviceToRoomController" as Controller
participant ":DeviceService" as Service
participant ":DeviceRepository" as Repository
participant ":DeviceFactory" as Factory
participant "device :Device" as Device
participant ":DeviceAssembler" as DeviceAssembler
participant "deviceDTO :DeviceDTO" as DeviceDTO
autonumber

note left of Controller
    List of Room's
    in US03
end note

User o-> Controller : addDeviceToRoom(roomDTO, deviceID)
activate Controller

Controller -> Service : addDevice(deviceID)
activate Service

Service -> Factory : createDevice(deviceID)
activate Factory

create Device
Factory -> Device : create(deviceID)

activate Device
Device --> Factory : device
deactivate Device

Factory --> Repository : device
deactivate Factory

activate Repository
Repository -> Repository : save(device)
Repository --> Service : device
deactivate Repository

loop
Service -> DeviceAssembler : device2DTO(device)
create DeviceDTO

activate DeviceAssembler
DeviceAssembler -> DeviceDTO : createDeviceDTO(device)

activate DeviceDTO
DeviceDTO --> DeviceAssembler : deviceDTO
deactivate DeviceDTO

DeviceAssembler --> Service : deviceDTO
deactivate DeviceAssembler

end loop
Service --> Controller : deviceDTO
deactivate Service

Controller --> User : deviceDTO
deactivate Controller
@enduml
