@startuml
'https://plantuml.com/sequence-diagram
participant " " as User
participant ":UC06_Controller" as UC06_Controller
participant ":RoomAssembler" as RoomAssembler
participant ":RoomDTO" as RoomDTO


participant ":DeviceAssembler" as DeviceAssembler
participant ":DeviceDTO" as DeviceDTO

participant ":House" as House
participant ":Room" as Room


autonumber


User o-> UC06_Controller: getRooms()

activate UC06_Controller

UC06_Controller -> House: getRooms()

activate House

House --> UC06_Controller: copyListOfRooms

deactivate House


loop for each room in copyListOfRooms

UC06_Controller -> RoomAssembler: domain2DTO(copyListOfRooms)


deactivate House

activate RoomAssembler

create  RoomDTO

RoomAssembler --> RoomDTO: domain2DTO(copyListOfRooms)

activate RoomDTO

RoomDTO --> RoomAssembler: roomsDTO

deactivate RoomDTO

RoomAssembler --> UC06_Controller: roomsDTO

deactivate RoomAssembler
end loop
User <--UC06_Controller : listOfRoomsDTO


User o-> UC06_Controller: getDevices(roomDTO)

UC06_Controller -> RoomAssembler: DTO2Domain(roomDTO)

activate RoomAssembler

RoomAssembler --> UC06_Controller : room

deactivate RoomAssembler


UC06_Controller -> Room: getDevices(room)

activate Room

Room --> UC06_Controller: copyDeviceList

deactivate Room

loop for each device in copyDeviceList

UC06_Controller -> DeviceAssembler: domain2DTO(copyDeviceList)


activate DeviceAssembler

create DeviceDTO

DeviceAssembler -> DeviceDTO: domain2DTO(copyDeviceList)

activate DeviceDTO

DeviceDTO --> DeviceAssembler: deviceListDTO

deactivate DeviceDTO

DeviceAssembler --> UC06_Controller: deviceListDTO

deactivate DeviceAssembler

 end loop

User <--UC06_Controller : deviceListDTO

deactivate UC06_Controller



@enduml

