@startuml
'https://plantuml.com/sequence-diagram
participant " " as User
participant ":GetListOfDevicesFromRoom_Controller" as GetListOfDevicesFromRoom_Controller

participant "serviceRoom:ServiceRoom" as ServiceRoom
participant "serviceDevice:ServiceDevice" as ServiceDevice

participant "roomRepo:RoomRepo" as RoomRepo
participant ":RoomAssembler" as RoomAssembler
participant "roomDTO:RoomDTO" as RoomDTO

participant "deviceRepo:DeviceRepo" as DeviceRepo
participant ":DeviceAssembler" as DeviceAssembler
participant "deviceDTO:DeviceDTO" as DeviceDTO

autonumber

User o-> GetListOfDevicesFromRoom_Controller: getRooms()

activate GetListOfDevicesFromRoom_Controller

GetListOfDevicesFromRoom_Controller -> ServiceRoom: getRooms()

activate ServiceRoom

ServiceRoom -> RoomRepo: findAll()

activate RoomRepo

RoomRepo --> ServiceRoom: listOfRooms

deactivate RoomRepo

ServiceRoom -> RoomAssembler : domainToDTO(listOfRooms)

activate RoomAssembler

loop for each room

    create RoomDTO

    RoomAssembler -> RoomDTO: createRoomDTO (room)

     activate RoomDTO

     RoomDTO --> RoomAssembler: roomDTO

      deactivate RoomDTO

     RoomAssembler -> RoomAssembler: addRoomDTOToList(roomDTO)

end
RoomAssembler --> ServiceRoom: roomDTOList

deactivate RoomAssembler

ServiceRoom --> GetListOfDevicesFromRoom_Controller: roomDTOList

deactivate ServiceRoom

GetListOfDevicesFromRoom_Controller --> User : roomDTOList

User o-> GetListOfDevicesFromRoom_Controller: getDevices(strRoomId)

GetListOfDevicesFromRoom_Controller -> ServiceDevice: getDevices(strRoomId)

activate ServiceDevice

ServiceDevice -> DeviceRepo: getDevicesByRoomId (roomId)

activate DeviceRepo

DeviceRepo --> ServiceDevice: listDevices

deactivate DeviceRepo

ServiceDevice  -> DeviceAssembler: deviceToDTO (deviceList)

activate DeviceAssembler

loop for each device in list
    create DeviceDTO

    DeviceAssembler -> DeviceDTO: createDeviceToDTO (device)

    activate DeviceDTO

    DeviceDTO --> DeviceAssembler: deviceDTO

    deactivate DeviceDTO

    DeviceAssembler -> DeviceAssembler: addDeviceDTOToList(deviceDTO)

end
DeviceAssembler --> ServiceDevice: listDeviceDTO

deactivate DeviceAssembler

ServiceDevice --> GetListOfDevicesFromRoom_Controller: listDeviceDTO

deactivate ServiceDevice

GetListOfDevicesFromRoom_Controller --> User : listDeviceDTO

deactivate GetListOfDevicesFromRoom_Controller






@enduml

