@startuml
'https://plantuml.com/sequence-diagram

participant " " as User

participant ":GetAllDevicesGroupedByFunctionalityController" as GetAllDevicesGroupedByFunctionalityController

participant "serDevType:ServiceDeviceType" as ServiceDeviceType

participant "serDev:ServiceDevice" as ServiceDevice

participant "repoDeviceType:RepositoryDeviceType" as RepositoryDeviceType

participant "repoDevice:RepositoryDevice" as RepositoryDevice

participant "DeviceTypeAssembler" as DeviceTypeAssembler

participant "deviceTypeDTO : DeviceType2StringDTO" as DeviceType2StringDTO

participant "DeviceAssembler" as DeviceAssembler

participant "deviceDTO : DeviceDTO" as DeviceDTO


autonumber

User o-> GetAllDevicesGroupedByFunctionalityController: getAllDevicesGroupedByFunctionality()

activate GetAllDevicesGroupedByFunctionalityController

GetAllDevicesGroupedByFunctionalityController -> ServiceDeviceType: getDeviceTypes()

activate ServiceDeviceType

ServiceDeviceType -> RepositoryDeviceType: findAll()

activate RepositoryDeviceType

RepositoryDeviceType --> ServiceDeviceType: deviceTypes

deactivate RepositoryDeviceType

loop for each deviceType in deviceTypes
    ServiceDeviceType -> DeviceTypeAssembler: deviceType2DTO(deviceType)

    activate DeviceTypeAssembler
    create DeviceType2StringDTO
    DeviceTypeAssembler -> DeviceType2StringDTO: deviceTypeAsString(deviceType)

    activate DeviceType2StringDTO

    DeviceType2StringDTO --> DeviceTypeAssembler: deviceTypeDTO

    deactivate DeviceType2StringDTO

    DeviceTypeAssembler --> ServiceDeviceType: deviceTypeDTO

    deactivate DeviceTypeAssembler

    ServiceDeviceType -> ServiceDeviceType: saveDeviceTypeDTO(deviceTypeDTO)

end

ServiceDeviceType --> GetAllDevicesGroupedByFunctionalityController : deviceTypeDTOs

deactivate ServiceDeviceType



GetAllDevicesGroupedByFunctionalityController -> ServiceDevice : getDevices()

activate ServiceDevice

ServiceDevice -> RepositoryDevice: findAll()

activate RepositoryDevice

RepositoryDevice --> ServiceDevice: devices

deactivate RepositoryDevice

loop for each device in devices
    ServiceDevice -> DeviceAssembler: device2DTO(device)

    activate DeviceAssembler
    create DeviceDTO
    DeviceAssembler -> DeviceDTO: createDeviceDTO(device)

    activate DeviceDTO

    DeviceDTO --> DeviceAssembler: deviceDTO

    deactivate DeviceDTO

    DeviceAssembler --> ServiceDevice: deviceDTO

    deactivate DeviceAssembler

    ServiceDevice -> ServiceDevice: saveDeviceDTO(deviceDTO)

end

ServiceDevice --> GetAllDevicesGroupedByFunctionalityController: deviceDTOs

deactivate ServiceDevice

GetAllDevicesGroupedByFunctionalityController -> GetAllDevicesGroupedByFunctionalityController: listDevicesByFunctionality(deviceTypeDTOs, deviceDTOs)

GetAllDevicesGroupedByFunctionalityController --> User: deviceDTOsByFunctionality

deactivate GetAllDevicesGroupedByFunctionalityController

@enduml