@startuml
!pragma layout smetana

participant " " as User
participant ":GetListOfAllMeasurementsOfOneDeviceController" as Controller

participant "period:DatePeriod" as DatePeriod
participant "deviceID:DeviceID" as DeviceID
participant ":DeviceService" as DeviceService
participant ":DeviceRepository" as DeviceRepository
participant ":LogService" as LogService
participant ":LogRepository" as Repository
participant ":LogAssembler" as Assembler
participant "logDTO:LogDTO" as DTO

autonumber

note right of User

  Ref UC06:
   I want to get a list of all
   devices in a room.
end note



User o-> Controller: getLogFromDevice(logDataDTO)

activate Controller
'DatePeriod and DeviceID are created
create DatePeriod
Controller -> DatePeriod: DatePeriod (start, end)
activate DatePeriod
DatePeriod --> Controller: period
deactivate DatePeriod

create DeviceID
Controller -> DeviceID: DeviceID (deviceID)
activate DeviceID
DeviceID --> Controller: deviceID
deactivate DeviceID

'getDeviceById -> if device is not present, return empty optional
Controller -> DeviceService: getDeviceById(deviceID)
activate DeviceService
DeviceService -> DeviceRepository: getDeviceById(deviceID)
activate DeviceRepository
DeviceRepository --> DeviceService: optionalDevice
deactivate DeviceRepository
DeviceService --> Controller: optionalDevice
deactivate DeviceService

'getAllMeasurementsOfDeviceInGivenPeriod -> getStartDate, getEndDate
Controller -> LogService: getDeviceReadingsByTimePeriod (deviceID, period)

'getStartDate -> localDateTimeStart
activate LogService

'findByDeviceIdAndTimeStampBetween -> look in all measurement repositories
LogService -> Repository: findByDeviceIdAndDatePeriodBetween(deviceID, period)

activate Repository
Repository --> LogService: logList

deactivate Repository
LogService --> Controller: logList


deactivate LogService
Controller -> Assembler: domainToDTO(logList)

activate Assembler
create DTO
Assembler -> DTO: LogDTO (log)
activate DTO
DTO --> Assembler: logDTO

deactivate DTO
Assembler --> Controller: logListDTO

deactivate Assembler
Controller --> User: logListDTO
deactivate Controller


@enduml