@startuml
'https://plantuml.com/use-case-diagram

skinparam actorStyle awesome
skinparam ActorBackgroundColor black

:Administrator: as Admin

(US03/UC03: To get list of rooms) as (Use3)

Admin -right-> (Use3)


@enduml