@startuml

!pragma layout smetana
autonumber

participant " " as User
participant ":AddRoomController" as Controller
participant "serviceRoom:ServiceRoom" as Service
participant ":RoomFactory" as Factory
participant "room :Room" as Room
participant ":RoomRepository" as Repository
participant ":RoomAssembler" as Assembler
participant "roomDTO :RoomDTO" as DTO

User o-> Controller: addRoom(roomDataDTO)
activate Controller
Controller -> Service: addRoom(houseID: String, name: String, int floor, int width, int length, int height): RoomDTO
activate Service
Service -> Factory: createRoom(houseID: HouseID, roomName: RoomName, dimension: Dimension, roomFloor: RoomFloor):Room
activate Factory
create Room
Factory -> Room: createRoom(HouseID houseID, RoomName name, Dimensions dimensions, Floor floor)
activate Room
Room --> Factory: room
deactivate Room
Factory --> Service: room
deactivate Factory
Service -> Repository: save(room)
activate Repository
Repository --> Service : room
deactivate Repository
Service -> Assembler: RoomDTO(room : Room)
activate Assembler
create DTO
Assembler -> DTO: roomDTO(String roomName, String roomDimension, String roomFloor, String roomID)
activate DTO
DTO --> Assembler: roomDTO
deactivate DTO
Assembler --> Service: roomDTO
deactivate Assembler
Service --> Controller: roomDTO
deactivate Service
Controller --> User: roomDTO
deactivate Controller





@enduml