@startuml
!pragma layout smetana

top to bottom direction
skinparam linetype ortho

class ConfigureHouseLocation<<Controller>>{
    -_houseService: HouseService
    +createHouseLocation(address, zipcode, gps):HouseService

}
class HouseFactory<<Factory>>{
    +createHouse(address, zipcode, gps):House
}
class HouseService <<Service>>{
    -_houseFactory: HouseFactory
    -_houseAssembler: HouseAssembler
    -_houseRepository: HouseRepository
    +createHouseLocation(address, zipcode, gps):Location
    +createHouse():HouseService
    +createAddress(street, doorNumber): String
    +createGps(latitude, longitude): String
    +createZipCode(): Int

}
class HouseDTO<<DTO>>{
    - _houseDTO: HouseDTO
    +address.tostring(): String
    +gps.toString: String
    +zipCode.toString(): String
}
class HouseAssembler<<Assembler>>{
    +domain2DTO():HouseDTO
}
class HouseRepository<<Repository>>{
    +saveHouse():House
    +getHouse():House
}

ConfigureHouseLocation "1" -down-> "1" HouseService: uses
HouseService "1" -left-> "1" HouseFactory : has >
HouseService "1" --[#595959,plain] "1" HouseAssembler : creates
HouseAssembler "1" --[#595959,plain] "1" HouseDTO : has >
HouseService "1" -right-> "1" HouseRepository : has >
@enduml