@startuml
'https://plantuml.com/sequence-diagram

class AddRoomToHouseController{
'Attributes'
- house: House

'Methods'
+addRoomToHouse(house : House)
-isValidConstructorArguments(house : House): boolean
+addRoomToHouse(name : String, floor : int, width : double, lenght : double, height : double) : RoomDTO
}

class House{
'Attributes'
-_locationFactory: LocationFactory
-_roomFactory: RoomFactory
-_location : Location
-_rooms: List<Room>

'Methods'
+House(locationFactory : LocationFactory, roomFactory : RoomFactory)
+addRoom(name : String, floor : int, width : double, lenght : double, height : double) : Room
+addRoomtoList(room : Room)
}


class Room{
'Attributes'
-_name : String
-_floor : int
-_dimensionsFactory : DimensionsFactory
-_dimensions : Dimensions
-_roomId : UUID
-_deviceList : List<Device>

'Methods'
#Room(name : String, floor : int, width : double, length : double, dimensionsFactory : DimensionsFactory)
-setDimensions(double width, double length, double height) : void
-setName(String name) : void
-setFloor(int floor) : void
-getName() : String
-getDimensions() : Dimensions
-getFloor() : int
}

class RoomFactory{
'Methods'
+createRoom(name : String, floor : int, width : double, length : double) : Room
}


class Dimensions{
'Atributes'
-_width: double
-_lenght: double
-_height: double

'Methods'
-setHeight(): void
-setLenght(): void
-setWidth(): void
+getHeigth(): double
+getLenght(): double
+getWidth(): double
+toString(): String
}

class DimensionsFactory{
'Methods'
+createDimensions(width : double, lenght : double, height : double) : Dimensions
}

class RoomAssembler{
'Methods'
+ <<static>> domain2DTO(room : Room) : RoomDTO
+ <<static>> domain2DTO(rooms : List<Room>) : List<RoomDTO>
+ <<static>> domain2Map(rooms : List<Room>) : Map<RoomDTO, Room>
}

class RoomDTO{
'Attributes'
+_name : String
+_dimensions : Dimensions
+_floor : int
+_roomId : UUID

'Methods'
+RoomDTO(room : Room)
}


AddRoomToHouseController "1" ..> "1" House: <<uses>>
House "1" ..> "1" RoomFactory: <<uses>>
RoomFactory "1" ..> "1" Room: <<creates>>
RoomFactory "1" ..> "1" DimensionsFactory: <<creates>>
DimensionsFactory "1" ..> "1" Dimensions: <<uses>>
AddRoomToHouseController "1" ..> "1"  RoomAssembler: <<uses>>
RoomAssembler  "1"..> "1" RoomDTO: <<creates>>
Room  "1"..> "1" DimensionsFactory: <<uses>>
House "1" *-- "0..*" Room: <<has>>

@enduml