@startuml
'https://plantuml.com/class-diagram

class GetListOfRoomsController{
'Attributes'
- _serviceRoom: RoomService
'Methods'
+GetListOfRooms_Controller(serviceRoom: ServiceRoom)
+getListOfRooms(): List<RoomDTO>
}

class RoomService{
'Attributes'
- _factoryRoom: RoomFactory
- _roomRepo: RoomRepository
- _roomAssembler : RoomAssembler
- _houseRepo: HouseRepository
'Methods'
+RoomService(factoryRoom: RoomFactory, roomRepo: RoomRepository, roomAssembler: RoomAssembler, houseRepo: HouseRepository)
+getRooms(): List<RoomDTO>
}


class RoomRepository{
'Attributes'
- _DATA: Map <RoomID, Room>
'Methods'
+RoomRepository()
+findAll(): List<Room>
}

class RoomAssembler{
'Methods'
+domainToDTO(rooms: List<Room>): List<RoomDTO>
}

class RoomDTO{
'Attributes'
+_roomID: RoomID
+_roomName: RoomName
'Methods'
+RoomDTO(room: Room)
}

GetListOfRoomsController "1" ..> "1" RoomService: uses
RoomService "1" ..> "1" RoomRepository: uses
RoomService "1" ..> "1" RoomAssembler: uses
RoomAssembler "1" ..> "*" RoomDTO: creates

@enduml