@startuml
!pragma layout smetana
top to bottom direction
skinparam linetype ortho

class AddSensorTypeController {
-CatalogueSensor catalogue
+AddSensorTypeController(Catalogue catalogue)
+getAllSupportedUnits(): List<String>
+addSensorType(String name, String units): SensorTypeDTO
}
class CatalogueSensor {
-List<SensorType> sensorTypes
+CatalogueSensor()
+addSensorType(String name, Unit units): SensorType
}
class SensorTypeFactory {

+createSensorType(String dscrp, Unit units): SensorType
}
class SensorType {
-String name
-Unit unit
+SensorType(String name, String units)
+getName(): String
+getUnits(): String
}
enum Unit {
+TEMPERATURE
+HUMIDITY
+getName(): String
+getUnit():String name
+getAllSupportedUnits(): List<String>
}
class SensorTypeAssembler {

+sensorTypeToDTO(SensorType sensorType): SensorTypeDTO

}
class SensorTypeDTO {
-String name
-String units
+SensorTypeDTO(String name, String units)
+getName(): String
+getUnits(): String
}

AddSensorTypeController "1"-->"1" CatalogueSensor: Uses
CatalogueSensor "1"--o "0..*  " SensorType: Composed
CatalogueSensor "1"--> "1" SensorTypeFactory: Uses
SensorTypeFactory "1"..> "1" SensorType: Creates
SensorType "*"--o "1" Unit: Has
AddSensorTypeController "1"-->"1     " SensorTypeAssembler: Uses
SensorTypeAssembler "1"..>"*" SensorTypeDTO: Creates


@enduml