@startuml
!pragma layout smetana

class Device {
  - _id: deviceID
  - _description: Description
  - _roomID: RoomID
  + Device(id: DeviceID, description: Description, houseID: HouseID)
  + getId(): string
  + getDescription(): Description
  + getRoomID(): RoomID
  }

class DeviceFactory {
  + createNewDevice(id: DeviceID, description: Description, houseID: HouseID): Device
  }

class DeviceRepository {
  - _map<ID, Device> device
  + addDeviceToRepository(device: Device): Device
  }
class DeviceService {
  - _deviceRepository: DeviceRepository
  - _deviceFactory: DeviceFactory
  - _deviceAssembler: DeviceAssembler
    + DeviceService(deviceRepository: DeviceRepository, deviceFactory: DeviceFactory, deviceAssembler: DeviceAssembler)
  + addDevice(strDeviceName: String, strRoomId: String): DeviceDTO
  }

 class RoomService{
  - _roomRepository: RoomRepository
  - _roomAssembler: RoomAssembler
  - _roomFactory: RoomFactory
  + RoomService(roomRepository: RoomRepository, roomAssembler: RoomAssembler, roomFactory: RoomFactory)
  + getRooms() : List<Room>
  }

class RoomRepository {
  - _data: Map<RoomID, Room>
  + findAll(): List<Room>
  }

class RoomAssembler {
    +RoomAssembler()
    +room2DTO(rooms: List<Room>): List<RoomDTO>
}

class RoomDTO {
    + id: string
    + name: string
    + houseID: string
    + RoomDTO(room: Room)
}

class AddDeviceToRoomController {
  - _deviceService: DeviceService
  - _roomService: RoomService
  + AddDeviceToRoomController(deviceService: DeviceService)
  + createNewDevice(roomID: String, deviceName: String): DeviceDTO
  + addDeviceToRepository(): boolean
  + getAllRooms(): List<RoomDTO>
  }
class DeviceDTO {
+ id: string
+ description: string
+ DeviceDTO(device: Device)
}
class DeviceAssembler{
  + domain2DTO(device: Device): DeviceDTO
  }


DeviceRepository "1" -down-> "1" Device: has
DeviceService "1".down.>"1  " DeviceFactory: uses
DeviceService "1".down.>"1" DeviceAssembler: uses
DeviceService "1".down.>"1" DeviceRepository: uses
RoomService "1".right.>"1" RoomRepository: uses
DeviceFactory "1".down.>"1  " Device: creates
AddDeviceToRoomController "1".down.>"1" DeviceService: uses
AddDeviceToRoomController "1".down.>"1" RoomService: uses
DeviceAssembler "1".up.> "*" DeviceDTO: creates
RoomService "1".down.>"1" RoomAssembler: uses
RoomAssembler "1".down.>"*" RoomDTO: creates


@enduml