@startuml
!pragma layout smetana

package SmartHome.sensors {

    class TemperatureSensor {
        - final _sensorType : SensorType
        - _value : TemperatureSensorValue
        + TemperatureSensor(catalogue : CatalogueSensor)
        + getSensorType() : SensorType
        + getValue() : Value
    }

    class TemperatureSensorValue implements SmartHome.domain.Value {
        - _nValue : double
        + TemperatureSensorValue(nValue : double)
        + toString() : String
    }

}

package SmartHome.domain {

    interface Sensor {
        + getSensorType() : SensorType
        + getValue() : Value
    }

    class SensorType {
        - _description : String
        - _unit : Unit
        # SensorType(description : String, unit : Unit)
        + getDescription() : String
        + getUnit() : Unit
    }

    interface Value {
    }

    class CatalogueSensor {
        + getSensorType(description : String) : SensorType
    }
}

SmartHome.sensors.TemperatureSensor ..|> SmartHome.domain.Sensor
SmartHome.sensors.TemperatureSensor "1" --> "1" SmartHome.domain.SensorType : has a
SmartHome.sensors.TemperatureSensor "1" --> "1" SmartHome.sensors.TemperatureSensorValue : contains
SmartHome.sensors.TemperatureSensor "1" ..> "1" SmartHome.domain.CatalogueSensor : uses
SmartHome.sensors.TemperatureSensorValue ..|> SmartHome.domain.Value
@enduml