@startuml
!pragma layout smetana

package domain.actuator {
    interface Actuator {
        + getActuatorID(): ActuatorID
        + setValue(Value value): Value
    }
    interface FactoryActuator {
        + createActuator(model: String, repoActuator: RepoActuator): Actuator
    }
    class ImplFactoryActuator {
        + createActuator(model: String, repoActuator: RepoActuator): Actuator
    }

    class SetIntegerActuator {
        - _actuatorID: ActuatorID
        - _actuatorTypeID: ActuatorTypeID
        - _actuatorModelID: ActuatorModelID
        - _deviceID: DeviceID
        - _value: SetIntegerValue
        - _lowerLimit: int
        - _upperLimit: int
        # SetIntegerActuator(actuatorTypeID: ActuatorTypeID, actuatorModelID: ActuatorModelID, deviceID: DeviceID, value: SetIntegerValue, lowerLimit: int, upperLimit: int)
        + getActuatorTypeString(): String
        + setValueInRange(Value value): Value
    }
}

package domain.value {
  class SetIntegerValue {
    - _value : int
    + SetIntegerValue(int value)
    + clone() : SetIntegerValue
    + toString() : String
  }
}

package valueObject {
    class ActuatorTypeID {
        - _description: String
        + ActuatorTypeID(String strDescription)
        + getType() : String
    }

    class ActuatorModelID {
        - _description: String
        + ActuatorModelID(String strDescription)
        + getModel() : String
    }

    class ActuatorID {
        - _id: String
        + ActuatorID(String id)
        + getID() : String
    }

    class DeviceID {
        - _id: String
        + DeviceID(String id)
        + getID() : String
    }
}

package ddd {

  interface DomainEntity {
  }

  interface DomainID {
  }

  interface AggregateRoot {
  }
}

ImplFactoryActuator ..|> FactoryActuator
ImplFactoryActuator "1" ..> "1" SetIntegerActuator : creates

SetIntegerActuator ..|> Actuator
SetIntegerActuator "1" --> "1" SetIntegerValue : has
SetIntegerActuator "1" -->  "1" ActuatorTypeID : has
SetIntegerActuator "1" -->  "1" ActuatorModelID : has
SetIntegerActuator "1" -->  "1" ActuatorID : has
SetIntegerActuator "1" -->  "1" DeviceID : has

DomainEntity --|> DomainID
AggregateRoot --|> DomainEntity
AggregateRoot --|> DomainID

Actuator ..|> ddd.AggregateRoot

ActuatorTypeID ..|> ddd.DomainID
ActuatorModelID ..|> ddd.DomainID
ActuatorID ..|> ddd.DomainID

@enduml
