@startuml

package SmartHome.sensors {

    class WindSensor {
        - final _sensorType : SensorType
        - _value : WindSensorValue
        + WindSensor(catalogue : CatalogueSensor)
        + getSensorType() : SensorType
        + getValue() : Value
    }

    class WindSensorValue implements SmartHome.domain.Value {
        - _speed : double
        - _direction : double
        + WindSensorValue(speed : double, direction : double)
        + getSpeed() : double
        + getDirection() : double
    }

}

package SmartHome.domain {

    interface Sensor {
        + getSensorType() : SensorType
        + getValue() : Value
    }

    class SensorType {
    }

    interface Value {
    }

    class CatalogueSensor {
        + getSensorType(description : String) : SensorType
    }
}

SmartHome.sensors.WindSensor ..|> SmartHome.domain.Sensor
SmartHome.sensors.WindSensor --> SmartHome.domain.SensorType : _sensorType
SmartHome.sensors.WindSensor --> SmartHome.sensors.WindSensorValue : _value
SmartHome.sensors.WindSensor --> SmartHome.domain.CatalogueSensor
SmartHome.sensors.WindSensorValue ..|> SmartHome.domain.Value

@enduml

@startuml

class WindSensor {
    - final _sensorType : SensorType
    - _value : WindSensorValue
    + WindSensor(catalogue : CatalogueSensor)
    + getSensorType() : SensorType
    + getValue() : Value
}

class WindSensorValue {
    - _speed : double
    - _direction : double
    + WindSensorValue(speed : double, direction : double)
    + getSpeed() : double
    + getDirection() : double
}

WindSensor --> WindSensorValue : _value

@enduml
