@startuml
!pragma layout smetana

package SmartHome.sensors {

    class DewPointSensor {
        - _sensorType : SensorType
        - _dewPointValue : DewPointValue

        + DewPointSensor (catalogue : CatalogueSensor)
        - setSensorType (catalogue : CatalogueSensor)
        +getSensorType () : SensorType
        +getValue () : Value
    }

    class DewPointValue implements SmartHome.domain.Value {
        - _dewPoint : int

        + DewPointValue(dewPointValue : int)
        + toString() : String
    }

}

package SmartHome.domain {

    interface Sensor {
        + getSensorType() : SensorType
        + getValue() : Value
    }

    class SensorType {
    - final _strDescription : String
    - final _unit : Unit

    + SensorType(strDescription : String, unit : Unit)
    - setStrDescription(strDescription : String) : String
    - setUnit(unit : Unit) : Unit
    + getStrDescription() : String
    + getUnit() : Unit
    }

    interface Value {
    }

    class CatalogueSensor {
    - _listSensorType : List<SensorType>
    - _listStringClassesSensor : List<String>

    + getSensorType(description : String) : SensorType
    }
}

SmartHome.sensors.DewPointSensor "1" ..|> "1" SmartHome.domain.Sensor : <<implements>>
SmartHome.sensors.DewPointSensor "1" --> "1" SmartHome.domain.SensorType : <<has>>
SmartHome.sensors.DewPointSensor "1" --> "1" SmartHome.sensors.DewPointValue : <<has>>
SmartHome.domain.CatalogueSensor "1" <.. "1" SmartHome.sensors.DewPointSensor : <<uses>>
SmartHome.sensors.DewPointValue "1" ..|> "1" SmartHome.domain.Value : <<implements>>

@enduml