@startuml
!pragma layout smetana

package domain.sensor {
    interface Sensor {
        + getSensorID(): SensorID
        + getValue(Value value): Value
    }
    interface FactorySensor {
        + createSensor(sensorModelID: sensorModelID, repoSensor: RepoSensor): Sensor
    }
    class ImplFactorySensor {
        + createSensor(sensorModelID: sensorModelID, repoSensor: RepoSensor): Sensor
    }

    class SolarIrradianceSensor {
        - _sensorID: SensorID
        - _sensorTypeID: SensorTypeID
        - _sensorModelID: SensorModelID
        - _deviceID: DeviceID
        - _value: SolarIrradianceValue
        # SolarIrradianceSensor(actuatorTypeID: ActuatorTypeID, actuatorModelID: ActuatorModelID, deviceID: DeviceID)
        + getSensorTypeString(): String
        + getSensorID(): SensorID
        + getValue(Value value): Value
    }
}

package domain.value {
  class SolarIrradianceValue {
    - _value : int
    + SolarIrradianceValue(int value)
    + toString() : String
  }
}

package valueObject {
    class SensorTypeID {
        - _description: String
        + SensorTypeID(String strDescription)
        + getTypeID() : String
    }

    class SensorModelID {
        - _description: String
        + SensorModelID(String strDescription)
        + getModelID() : String
    }

    class SensorID {
        - _id: String
        + SensorID(String id)
        + getID() : String
    }

    class DeviceID {
        - _id: String
        + DeviceID(String id)
        + getID() : String
    }
}

package ddd {

  interface DomainEntity {
  }

  interface DomainID {
  }

  interface AggregateRoot {
  }
}

ImplFactorySensor ..|> FactorySensor
ImplFactorySensor "1" ..> "1" SolarIrradianceSensor : creates

SolarIrradianceSensor ..|> Sensor
SolarIrradianceSensor "1" --> "1" SolarIrradianceValue : has
SolarIrradianceSensor "1" -->  "1" SensorTypeID : has
SolarIrradianceSensor "1" -->  "1" SensorModelID : has
SolarIrradianceSensor "1" -->  "1" SensorID : has
SolarIrradianceSensor "1" -->  "1" DeviceID : has

DomainEntity --|> DomainID
AggregateRoot --|> DomainEntity
AggregateRoot --|> DomainID

Sensor ..|> ddd.AggregateRoot

SensorTypeID ..|> ddd.DomainID
SensorModelID ..|> ddd.DomainID
SensorID ..|> ddd.DomainID

@enduml
