@startuml
'https://plantuml.com/sequence-diagram

!pragma layout smetana
skinparam actorStyle awesome
skinparam ActorBackgroundColor black

actor Administrator as Admin

(Add Room to House) as UC1

Admin -right-> UC1
@enduml