@startuml
'https://plantuml.com/use-case-diagram
'left to right direction
skinparam actorStyle awesome
skinparam ActorBackgroundColor black

:Administrator: as Admin
:Power User: as Power_User
:Room Owner: as Room_Owner

(US03/UC03: To get list of rooms) as (Use3)
(US06/UC06: To get list of devices) as (Use4)
(US07/UC07: To add sensor to device) as (Use7)

Admin -left-> (Use7)

Power_User -right-> (Use7)

Room_Owner -down-> (Use7)

(Use7) ..> (Use3): <<includes>>
(Use7) ..> (Use4): <<includes>>

@enduml