@startuml

participant " "
participant ":ConfigureHouseLocationController" as ConfigureHouseLocationController
participant ":HouseService" as Service
participant "address:Address" as Address
participant "zipCode:ZipCode" as ZipCode
participant "gps:Gps" as Gps
participant ":HouseFactory" as Factory
participant "house:House" as House
participant ":HouseRepository" as Repository
participant ":HouseAssembler" as Assembler
participant "houseDTO:HouseDTO" as DTO

'----------------------------------------------------------
autonumber
" " o-> ConfigureHouseLocationController : requestconfigureHouseLocation(houseDTO)
activate ConfigureHouseLocationController
ConfigureHouseLocationController -> ConfigureHouseLocationController : createLocationDTO(street, doorNumber, zipCode, latitude, longitude)
ConfigureHouseLocationController -> Service : createHouseLocation(street, doorNumber, zipCode, latitude, longitude)
activate Service

Service -> Factory : createHouseLocation(address, zipCode, gps)
activate Factory
create House
Factory -> House: createHouse(address, zipCode, gps)
activate House
House --> Factory: house
deactivate House
Factory --> Service: house
deactivate Factory
Service -> Repository : saveHouse(house)
activate Repository
deactivate Service
Repository --> ConfigureHouseLocationController : house
deactivate Repository
ConfigureHouseLocationController -> Assembler : assemblerHouseLocation(house)
activate Assembler
create DTO
Assembler -> DTO : house2DTO(house)
activate DTO
DTO --> Assembler : houseDTO
deactivate DTO
Assembler --> ConfigureHouseLocationController : houseDTO
deactivate Assembler

" " <-- ConfigureHouseLocationController : houseDTO
deactivate ConfigureHouseLocationController

@enduml