@startuml
'https://plantuml.com/sequence-diagram
!pragma layout smetana

autonumber

participant " " as User

box "Server"
    participant "Controller" as Controller
    participant "Service" as Service
    participant "Repository" as Repo
    participant "Domain" as Domain
end box

    participant "DataBase" as BD

User o-> Controller : POST /actuator (json)
activate Controller

'Controller -> Controller: actuatorEntryDTO = deserialize(json)

'Controller -> Controller: actuatorParameters = getActuatorParameters(actuatorEntryDTO)

Controller -> Service : addActuator(actuatorParameters)
activate Service

Service -> Domain: actuator = create(actuatorParameters)
activate Domain
deactivate Domain

Service -> Repo : save(actuator)
activate Repo

Repo ->o BD : save(actuator)

Repo --> Service : actuator
deactivate Repo

Service --> Controller : actuator
deactivate Service

'Controller -> Controller : actuatorDTO = domainToDTO(actuator)

'Controller -> Controller : json = serialize(actuatorDTO)

Controller -->o User : json 201
deactivate Controller


@enduml