@startuml
'https://plantuml.com/sequence-diagram
!pragma layout smetana
autonumber

participant " " as HTTP

box "Server"
    participant "Controller" as Controller
    participant Service as Service
    participant Repository as Repository
    participant BlindRollerActuator as BlindRollerActuator

    end box

    participant DataBase as " "


HTTP -> Controller: POST/set-blindRoller
activate Controller

Controller -> Service: getDeviceReadings (deviceID, sensorTypeID)
activate Service

Service -> Repository: getDeviceReadings (deviceID, sensorTypeID)
activate Repository

Repository ->o DataBase: findAll()

DataBase o--> Repository: deviceReadingsList

Repository --> Service: deviceReadingsList
deactivate Repository

Service --> Controller: deviceReadingsList
deactivate Service

Controller -> Service: setValue (actuatorBlindRoller, blindRollerValue, blindRollerCurrentValue)
activate Service

Service -> BlindRollerActuator: setValue(blindRollerValue)
activate BlindRollerActuator

BlindRollerActuator --> Service: blindRollerValue
deactivate BlindRollerActuator

Service --> Controller: blindRollerValue
deactivate Service

Controller --> HTTP: JSON / Status 201


@enduml