@startuml
'https://plantuml.com/sequence-diagram
!pragma layout smetana

autonumber

participant " " as User

box "SmartHome"
    participant "Controller" as CTRL
    participant "Service" as SV
    participant "Repository" as REPO
    participant "Domain" as DOM
end box
    participant " " as BD



User o-> CTRL : GET /devices?room_id={roomId}&device_type_id={Temperature}

activate CTRL

CTRL -> DOM : RoomID(strRoomID)
activate DOM

DOM --> CTRL : roomID
deactivate DOM

CTRL -> SV: getDevicesByRoomID(roomID)
activate SV

SV -> REPO : findByRoomID(roomID)
activate REPO

REPO ->o BD : find


BD o--> REPO : deviceDataModelList

REPO --> SV : deviceList
deactivate REPO

SV --> CTRL : deviceList
deactivate REPO
deactivate SV

CTRL -> DOM : deviceTypeID(strDeviceType)
activate DOM

DOM --> CTRL : deviceTypeID
deactivate DOM

CTRL -> SV : getDevicesByDeviceTypeID(deviceTypeID)
activate SV

SV -> REPO : findByDeviceTypeID(deviceTypeID)
activate REPO

REPO ->o BD : find

BD o--> REPO : deviceDataModelList

REPO --> SV : deviceList
deactivate REPO

SV --> CTRL : deviceList
deactivate SV

CTRL -->o User : Json/status 200
deactivate CTRL



@enduml