@startuml
'https://plantuml.com/sequence-diagram
!pragma layout smetana

autonumber

actor "User" as User
participant "RestClient" as RC

box "SmartHome"
    participant "Server" as SV
    participant "DataBase" as BD
end box

User -> RC : I want to get all devices grouped by functionality
activate RC

RC -> SV : getAllDevicesGroupedByFunctionality()
activate SV

SV -> BD : findAll()
activate BD

BD --> SV : deviceDataModelList
deactivate BD

SV --> RC : deviceDTOListGroupedByFunctionality
deactivate SV

RC --> User : deviceDTOListGroupedByFunctionality
deactivate RC


@enduml