@startuml
'https://plantuml.com/sequence-diagram
!pragma layout smetana

autonumber

actor "User" as User
participant "RestClient" as RC

box "SmartHome"
    participant "Controller" as CTRL
    participant "Service" as SV
    participant "Repository" as REPO
    participant "DataBase" as BD
end box

User -> RC : want to have a list of existing rooms
activate RC

RC -> CTRL : getAllRooms()
activate CTRL


CTRL -> SV : getAllRooms()
activate SV

SV -> REPO : findAll()
activate REPO

REPO -> BD : find
activate BD

BD --> REPO : roomDataModelList
deactivate BD

REPO --> SV : roomList
deactivate REPO

SV --> CTRL : roomList
deactivate SV

CTRL --> RC : roomDTOList
deactivate CTRL

RC --> User : roomDTOList
deactivate RC


@enduml