@startuml
'https://plantuml.com/sequence-diagram
!pragma layout smetana

autonumber

participant " " as HTTP

box "Server"
participant "Routing" as ROUT
    participant "Controller" as CTRL
    participant "Service" as SV
    participant "Repository" as REPO
    participant "Domain" as DOM
end box
participant " " as BD

HTTP -> ROUT : POST /device
activate ROUT

ROUT -> CTRL : addDevice (deviceEntryDTO)
activate CTRL

CTRL -> DOM : RoomID(idStr)
activate DOM
DOM --> CTRL : roomID
deactivate DOM

CTRL -> DOM : DeviceName(strName)
activate DOM
DOM --> CTRL : deviceName
deactivate DOM

CTRL -> DOM : DeviceTypeID(idStr)
activate DOM
DOM --> CTRL : deviceTypeID
deactivate DOM

CTRL -> SV : addDevice(roomID, deviceName, deviceTypeID)
activate SV

SV -> REPO : save(device)
activate REPO
REPO ->o BD : save


REPO --> SV : device
deactivate REPO

SV --> CTRL : device
deactivate SV

CTRL --> ROUT : deviceDTO
deactivate CTRL

ROUT --> HTTP : JSON Status ok
deactivate ROUT


@enduml