@startuml
'https://plantuml.com/sequence-diagram

participant " " as User
box "Power Consumption"
participant Controller as "Controller"
participant Service as "Service"
participant Repository as "Repository"
participant Domain as "Domain"
end box

participant DataBase as " "


autonumber


User o-> Controller: GET /logs/temperature-difference?outsideDeviceIDStr={outsideDeviceIDStr}&insideDeviceIDStr={insideDeviceIDStr}&initialTime={initialTime}&finalTime={finalTime}&timeDelta={timeDelta} (outsideDeviceDTO, insideDeviceDTO, initialTime, endTime, timeDelta)

activate Controller

Controller -> Domain :DeviceID(outsideDeviceIDStr)
activate Domain

Domain --> Controller : deviceID
deactivate Domain

Controller -> Domain: DeviceID(insideDeviceIDStr)
activate Domain

Domain --> Controller : deviceID
deactivate Domain

Controller -> Domain: SensorType(strTemperature)
activate Domain

Domain --> Controller : sensorType
deactivate Domain

Controller -> Domain: DatePeriod(initialTime, endTime)
activate Domain

Domain --> Controller : datePeriod
deactivate Domain

Controller -> Domain: TimeDelta(intTimeDelta)
activate Domain

Domain --> Controller : timeDelta
deactivate Domain

Controller -> Service: getMaxInstTempDiffBetweenDeviceAndOutside(insideDeviceID, sensorType, timeDelta)
activate Service

Service -> Repository: findByDeviceIDAndSensorTypeAndDatePeriodBetween(deviceID, sensorTypeID, period)

activate Repository

Repository ->o DataBase: find


DataBase o--> Repository: logList

Repository --> Service: logInsideReadingsList
deactivate Repository

Service --> Controller: logInsideReadingsList
deactivate Service

Controller -> Service: getMaxInstTempDiffBetweenDeviceAndOutside(outsideDeviceID, sensorType, timeDelta)
activate Service

Service -> Repository: findByDeviceIDAndSensorTypeAndDatePeriodBetween(deviceID, sensorTypeID, period)

activate Repository

Repository ->o DataBase: find

DataBase o--> Repository: loglist



Repository --> Service: listLogsOutsideReadings
deactivate Repository

Service --> Controller: listLogsOutsideReadings
deactivate Service

Controller -> Service: getMaxInstTempDiffBetweenDeviceAndOutside(insideReadings, outsideReadings, timeDelta)
activate Service

Service --> Controller: maxInstTempDiff
deactivate Service

Controller -->o User: JSON, status 200
deactivate Controller







@enduml