@startuml
'https://plantuml.com/sequence-diagram
!pragma layout smetana

autonumber


participant " " as HTTP

box "Server"
    participant "Controller" as CTRL
    participant "Service" as SV
    participant "Repository" as REPO
    participant "Domain" as DOM

end box
participant "DataBase" as BD


HTTP -> CTRL : POST /house
activate CTRL


CTRL -> DOM : createAddress(street, doorNumber, postalCode, countryCode, postalCodeFactory)
activate DOM
DOM --> CTRL : address

CTRL -> DOM : createGPS(latitude, longitude)
DOM --> CTRL : gps
deactivate DOM

CTRL -> SV : addHouse(address, gps)
activate SV

SV -> REPO : save(house)
activate REPO
REPO -> BD : save
REPO --> SV : house
deactivate REPO

SV --> CTRL : house
deactivate SV


CTRL --> HTTP : houseDTO
deactivate CTRL


deactivate HTTP


@enduml