@startuml
'https://plantuml.com/sequence-diagram
!pragma layout smetana

autonumber

participant " " as User

box "Server"
    participant "Controller" as CTRL
    participant "Service" as SV
    participant "Repository" as REPO
    participant "Domain" as DOM
end box

participant " " as BD

User o-> CTRL : GET /logs?deviceID={deviceID}&timeStart={timeStart}&timeEnd={timeEnd}
activate CTRL
CTRL -> DOM : DatePeriod (start, end)
activate DOM
DOM --> CTRL : datePeriod
deactivate DOM

CTRL -> DOM : DeviceID(strDeviceID)
activate DOM
DOM --> CTRL : deviceID
deactivate DOM

CTRL -> SV : getDeviceReadingsByTimePeriod (deviceID, period)
activate SV

SV -> REPO : findByDeviceIdAndDatePeriodBetween(deviceID, period)
activate REPO

REPO ->o BD : find
BD o--> REPO : readings

REPO --> SV : logList
deactivate REPO

SV --> CTRL : logList
deactivate SV
CTRL -->o User : json 200
deactivate CTRL


@enduml