@startuml
!pragma layout smetana

package SmartHome.actuators {

  class SetIntegerActuator {
    - _actuatorType: ActuatorType
    - _value: SetIntegerValue
    - _lowerLimit: int
    - _upperLimit: int
    + SetIntegerActuator(CatalogueActuator catalogue)
    - setActuatorType(CatalogueActuator catalogue) : void
    - setLowerLimit(int lowerLimit) : int
    - setUpperLimit(int upperLimit) : int
    + getActuatorType(): ActuatorType
    + setValueInRange(int lowerLimit, int upperLimit, Value value): Value

  }

  class SetIntegerValue {
    - _value : int
    + SetIntegerValue(int value)
    - setValue(int value) : void
    + clone() : SetIntegerValue
    + toString() : String
  }

}

package SmartHome.domain {

  interface Actuator {
        + getActuatorType(): ActuatorType
  }

  interface Value {
  }

  class ActuatorType {
    - _description: String
    # ActuatorType(String strDescription)
    - setStrDescription(String strDescription) : void
    + getDescription() : String
  }

 class CatalogueActuator {
    - _listActuatorTypes: List<ActuatorType>
    - _listStringClassesActuator : List<String>
    + CatalogueActuator(String filePathname)
    - validateConstructorParameters(String strDescription): boolean
    + addActuatorType(String strDescription, ActuatorTypeFactory actuatorTypeFactory): ActuatorType
    + addActuatorTypeToList(ActuatorType actuatorType): ActuatorType
    + getActuatorTypes(): List<ActuatorType>
    + getActuatorType(String strDescription): ActuatorType
    + getActuatorModels(): List<String>
    + getActuator(String strModel, ActuatorFactory actuatorFactory): Actuator
  }


}

SmartHome.actuators.SetIntegerActuator "1" ..|>  "1" SmartHome.domain.Actuator : <<implements>>
SmartHome.actuators.SetIntegerActuator --> SmartHome.domain.ActuatorType : <<has>>
SmartHome.actuators.SetIntegerActuator --> SmartHome.actuators.SetIntegerValue : <<has>>
SmartHome.actuators.SetIntegerValue ..|> SmartHome.domain.Value : <<implements>>
SmartHome.actuators.SetIntegerActuator ..> SmartHome.domain.CatalogueActuator : <<uses>>

@enduml
