@startuml
!pragma layout smetana

package SmartHome.AgregateDevice {
class Device<<entity>><<Root>>{
    - _deviceID: DeviceID
    - _deviceTypeID: DeviceTypeID
    - _roomID: RoomID
    - _name: Name
}
}

package SmartHome.ValueObject {
    class DeviceID<<value object>>{
        - _id: String
    }
    class Name<<value object>>{
        - _name: String
    }

    class DeviceTypeID<<value object>>{
        - _id: String
    }

    class RoomID<<value object>>{
        - _id: String
    }
}

Device "*" -- "1" DeviceID : has
Device "*" -- "1" Name : has
Device "*" -- "1" DeviceTypeID : has
Device "*" -- "1" RoomID : has
@enduml