@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "User" as User
participant "RestClient" as RC
participant "SmartHome" as SH


User -> RC : I want to configure the house location
activate RC

RC -> SH : configureHouseLocation(houseDataDTO)
activate SH

SH --> RC : houseDTO
deactivate SH

RC --> User : houseDTO
deactivate RC



@enduml