@startuml
'https://plantuml.com/sequence-diagram
!pragma layout smetana

autonumber

participant " " as HTTP

box "Backend"
    participant "Backend" as BE
end box

HTTP -> BE : GET /actuators?deviceID={deviceID}
activate BE


BE --> HTTP : listActuatorsDTO
deactivate BE



@enduml