@startuml
'https://plantuml.com/sequence-diagram
!pragma layout smetana

autonumber


participant " " as HTTP

box "SmartHome"
    participant "Backend" as BE

end box

HTTP -> BE : POST /house
activate BE
BE -> HTTP : houseDTO
deactivate BE

@enduml
