@startuml
'https://plantuml.com/sequence-diagram
!pragma layout smetana

autonumber

participant " " as HTTP

box "SmartHome"
    participant "Frontend" as FE
    participant "Backend" as BE

end box


HTTP o-> FE : I want the maximum instantaneous temperature difference between outside and inside
activate FE

FE -> BE : GET /temperature
activate BE

BE --> FE : JSON, status 200
deactivate BE

FE -->o HTTP : temperature
deactivate FE




@enduml