@startuml
'https://plantuml.com/sequence-diagram
!pragma layout smetana

autonumber

participant " " as User

box "SmartHome"
    participant "Frontend" as FE
    participant "Backend" as SV
end box

User o-> FE : GET /devices
activate FE

FE -> SV : GET /devices?room_id={roomId}
activate SV

SV --> FE : Json, status OK
deactivate SV

FE -->o User : status OK
deactivate FE


@enduml