@startuml
'https://plantuml.com/sequence-diagram
!pragma layout smetana

autonumber

participant  " "  as HTTP
box "Smart Home"
    participant "Backend" as BE
end box

HTTP o-> BE : PUT /device/deactivate/{id}
activate BE

BE -->o HTTP : JSON 200 OK
deactivate BE

@enduml
