@startuml
'https://plantuml.com/sequence-diagram
!pragma layout smetana

autonumber

participant " " as User
    box SmartHome
    participant Frontend as FE
    participant Backend as BE
    end box


User o-> FE :  GET / configureDevice
activate FE

FE -> BE : POST /sensors
activate BE

BE --> FE : Json, status CREATED
deactivate BE

FE -> BE : POST /actuators
activate BE

BE --> FE :  Json, status CREATED
deactivate BE

FE -->o User : status CREATED
deactivate FE





@endumll