@startuml
'https://plantuml.com/sequence-diagram
!pragma layout smetana

autonumber



    box SmartHome
    participant Frontend as FE
    participant WeatherService as WS
    end box



[o-> FE : I want to have current outside temperature on the main page
activate FE

FE -> WS : POST / WeatherServiceConfiguration
activate WS

WS --> FE : json, status CREATED

WS -> WS : GET / InstantaneousTemperature

WS --> FE : json, status OK
deactivate WS

[o<-- FE : json, status OK
deactivate FE




@enduml