@startuml
'https://plantuml.com/sequence-diagram

!pragma layout smetana

autonumber

actor "User" as User
participant "RestClient" as RC
box "Smart Home"
    participant "Server" as Server
    participant "Database" as DB
end box

User -> RC : I want to get the log from a device, in a time period
activate RC

RC -> Server : getDeviceReadingsByTimePeriod(logDataDTO)
activate Server

Server -> DB : findByDeviceIDAndTimestampBetween(deviceID, startDate, endDate)
activate DB

DB --> Server : logDataModelList
deactivate DB

Server --> RC : logDTOList
deactivate Server

RC --> User : logDTOList
deactivate RC

@enduml