@startuml
'https://plantuml.com/sequence-diagram

!pragma layout smetana

autonumber

participant " " as HTTP

box "SmartHome"
    participant "Frontend" as FE
    participant "Backend" as BE

end box
HTTP o-> FE: I want to get the devices with temperature functionality from a room
activate FE

FE -> BE : GET /grouped devices with temperature functionality
activate BE

BE --> FE : JSON, status 200
deactivate BE

FE -->o HTTP : devices

@enduml