@startuml
'https://plantuml.com/sequence-diagram
!pragma layout smetana

autonumber
participant " " as User

box "SmartHome"
    participant Frontend as FE
    participant Backend as BE
end box


User o-> FE : I want to add a new device to a room
activate FE

FE -> BE : POST /devices
activate BE

BE --> FE : Json, 201
deactivate BE

FE -->o User : Json, 201
deactivate FE



@enduml