@startuml
'https://plantuml.com/sequence-diagram

!pragma layout smetana

autonumber

participant " " as HTTP

box "Smart Home"
    participant "Backend" as BE
end box

HTTP -> BE : POST /sensor-types

activate BE

BE --> HTTP : JSON/ status 201
deactivate BE




@enduml