@startuml
'https://plantuml.com/sequence-diagram
!pragma layout smetana

autonumber

participant " " as User


box "SmartHome"
    participant "Frontend" as FE
    participant "Backend" as SV
end box

User o-> FE : GET /rooms
activate FE

FE -> SV : GET /rooms
activate SV

SV --> FE : HTTP 200 Ok
deactivate SV

FE -->o User : ok
deactivate FE


@enduml