@startuml
'https://plantuml.com/sequence-diagram
!pragma layout smetana

autonumber
actor "User" as User

box "SmartHome"
    participant Frontend as FE
end box

User -> FE : I want to have today’s sunrise and sunset hours on the front/main page
activate FE

FE -> API : fetch (https://api.sunrise-sunset.org/jason)
activate API
API --> FE : get sunrise and sunset hours
deactivate API

FE --> User : show sunrise and sunset hours
deactivate FE



@enduml