@startuml
'https://plantuml.com/sequence-diagram
!pragma layout smetana

autonumber


participant " " as HTTP
box "Smart Home"
    participant "Backend" as BE
end box

HTTP o-> BE : GET /devices?room_id={roomId}
activate BE

BE -->o HTTP : Json status 200 ok
deactivate BE

@enduml