@startuml
'https://plantuml.com/sequence-diagram
!pragma layout smetana

autonumber

actor "User" as User
participant "RestClient" as RC

box "SmartHome"
    participant "Server" as SV
    participant "DataBase" as BD
end box

User -> RC :  I want to get the peak power consumption of the house, in a given period
activate RC

RC -> SV : getMaxPowerConsumption (initialTime, endTime)
activate SV

SV -> BD : getMaxPowerConsumptionReadings (initialTime, endTime)
activate BD

BD --> SV : listLogDataModel
deactivate BD

SV --> RC : maxConsumption
deactivate SV

RC --> User : maxConsumption
deactivate RC


@enduml