@startuml
'https://plantuml.com/sequence-diagram
!pragma layout smetana

autonumber
participant " " as User

box "SmartHome"
    participant Frontend as FE
    participant Backend as BE
end box

User o-> FE : POST /device
activate FE

FE -> BE : POST /device
activate BE
BE --> FE : HTTP status 200
deactivate BE

FE -->o User : ok
deactivate FE



@enduml