@startuml
'https://plantuml.com/sequence-diagram
!pragma layout smetana

autonumber


participant " " as HTTP

box "SmartHome"
    participant "Backend" as BE

end box

" " -> BE : POST /house

activate BE
BE -> " " : houseDTO
deactivate BE

@enduml
