@startuml
'https://plantuml.com/class-diagram

class GetListOfDevicesFromRoomController{
'Attributes'
- _roomService: RoomService
- _deviceService : DeviceService
- _roomAssembler : RoomAssembler
- _deviceAssembler : DeviceAssembler
'Methods'
+GetListOfDevicesFromRoomController (serviceRoom : RoomService, serviceDevice : DeviceService, roomAssembler : RoomAssembler ,deviceAssembler : DeviceAssembler)
+getRooms(): List<RoomDTO>
+getDevices(roomDTO: RoomDTO): List<DeviceDTO>
}

class RoomService{
'Attributes'
- _roomRepository: RoomRepository
-_roomFactory : RoomFactory
- _roomAssembler : RoomAssembler
- _houseRepository : HouseRepository
'Methods'
+RoomService(roomRepository: RoomRepository, roomFactory: RoomFactory, roomAssembler : RoomAssembler, houseRepo : HouseRepository)
+getRooms(): List<RoomDTO>
+getRoomById (roomID : RoomID): Option<Room>
}


class RoomRepository{
'Attributes'
- DATA: Map <RoomID, Room>
'Methods'
+RoomRepository()
+findAll(): List<Room>
+ofIdentity (id : RoomID): Option<Room>
}

class RoomAssembler{
'Methods'
+domainToDTO(rooms: List<Room>): List<RoomDTO>
}

class RoomDTO{
'Attributes'
+roomID: String
+roomName: String
+dimensions : String
+floor : String
'Methods'
+RoomDTO(roomName : String, roomDimension : String, floor : String, roomID : String)
}

class RoomID{
'Attributes'
- _roomID: String

'Methods'
+RoomID(roomID: String)
}

class DeviceService{
'Attributes'
- _deviceRepository: DeviceRepository
- _deviceFactory : DeviceFactory
- _roomRepository : RoomRepository

'Methods'
+DeviceService(deviceRepository: DeviceRepository, deviceFactory: DeviceFactory, roomRepository : RoomRepository)
+getDevicesByRoomId(roomID : RoomID): List<Device>
}

class DeviceRepository{
'Attributes'
- -deviceData: Map <DeviceId, Device>
'Methods'
+DeviceRepository()
+findByRoomId(roomId : RoomID): List<Devices>
}

class DeviceAssembler {
'Methods'
+domainToDTO(devices: List<Device>): List<DeviceDTO>
}

class DeviceDTO{
'Attributes'
+deviceID: String
+deviceName: String
+roomID : String
+deviceStatus : String
'Methods'
+DeviceDTO(deviceID : String, deviceName : String, roomID : String, deviceStatus : String)
}



GetListOfDevicesFromRoomController "1" ..> "1" RoomService: uses
RoomService "1" ..> "1" RoomRepository: uses
GetListOfDevicesFromRoomController "1" ..> "1" RoomAssembler: uses
RoomAssembler "1" ..> "*" RoomDTO: creates

GetListOfDevicesFromRoomController "1" ..> "1" DeviceService: uses
DeviceService "1" ..> "1" DeviceRepository: uses
GetListOfDevicesFromRoomController "1" ..> "1" DeviceAssembler: uses
DeviceAssembler "1" ..> "*" DeviceDTO: creates

GetListOfDevicesFromRoomController "1" ..> "1" RoomID: creates
@enduml