@startuml
'https://plantuml.com/sequence-diagram

actor "Room Owner/Administrator/Power User" as RoomOwner

RoomOwner -> System: I want to have a list of devices from a room
System --> RoomOwner: What room?
RoomOwner -> System: This room
System --> RoomOwner: list of devices


@enduml