@startuml
'https://plantuml.com/sequence-diagram
!pragma layout smetana

autonumber

participant " " as HTTP

box "Server"
    participant "Controller" as CTRL
    participant "Service" as SV
    participant "Repository" as REPO
    participant "Domain" as DOM

end box
participant "DataBase" as BD


HTTP -> CTRL : POST /Room
activate CTRL



CTRL -> DOM : RoomName (strName)
activate DOM
DOM --> CTRL : roomName
deactivate DOM

CTRL -> DOM : Dimension (intWidth, intLength, intHeight)
activate DOM
DOM --> CTRL : dimension
deactivate DOM

CTRL -> DOM : RoomFloor (intFloor)
activate DOM
DOM --> CTRL : roomFloor
deactivate DOM

CTRL -> SV :addRoom(roomName,dimension,roomFloor)
activate SV

SV -> REPO : save(room)
activate REPO
REPO -> BD : save
activate BD
deactivate BD
REPO --> SV : room
deactivate REPO

SV --> CTRL : room
deactivate SV


CTRL --> HTTP : roomDTO
deactivate CTRL





@enduml