@startuml
!pragma layout smetana
'As a Power User, I want the system to have a type of sensor that gives the current value/position in a scale %.'

actor PowerUser
participant System

PowerUser -> System: I want to get Current Position in Percentage Scale
System --> PowerUser: Which o sensor?
PowerUser -> System: !Temperature
System --> PowerUser: What is the value return ?
PowerUser -> System: !value
System --> PowerUser: The sensor has been create to the system
@enduml
