@startuml
!pragma layout smetana

class Device {
  - _id: deviceID
  - _name: DeviceName
  - _roomID: RoomID
  + Device(name: DeviceName, houseID: HouseID)
  + getId(): string
  + getDescription(): Description
  + getRoomID(): RoomID
  }

class DeviceFactory {
  + createNewDevice(id: DeviceID, name: DeviceName, roomID: RoomID): Device
  }

class DeviceRepository {
  - _map<ID, Device> device
  + addDeviceToRepository(device: Device): Device
  }
class DeviceService {
  - _deviceRepository: DeviceRepository
  - _deviceFactory: DeviceFactory
  - _deviceAssembler: DeviceAssembler
  - _roomRepository: RoomRepository
    + DeviceService(roomRepository: RoomRepository, deviceRepository: DeviceRepository, deviceFactory: DeviceFactory, deviceAssembler: DeviceAssembler)
  + addDevice(strDeviceName: String, strRoomId: String): DeviceDTO
  }

 class RoomService{
  - _roomRepository: RoomRepository
  - _roomAssembler: RoomAssembler
  - _roomFactory: RoomFactory
  - _houseRepository: HouseRepository
  + RoomService(houseRepository: HouseRepository, roomRepository: RoomRepository, roomAssembler: RoomAssembler, roomFactory: RoomFactory)
  + getRooms() : List<Room>
  }

class RoomRepository {
  - _data: Map<RoomID, Room>
  + findAll(): List<Room>
  }

class RoomAssembler {
    +RoomAssembler()
    +roomToDTO(rooms: List<Room>): List<RoomDTO>
}

class RoomDTO {
    + id: string
    + name: string
    + RoomDTO(room: Room)
}

class AddDeviceToRoomController {
  - _deviceService: DeviceService
  - _roomService: RoomService
  + AddDeviceToRoomController(roomService: RoomService, deviceService: DeviceService)
  + addDeviceToRoom(roomID: String, deviceName: String): DeviceDTO
  + getAllRooms(): List<RoomDTO>
  }
class DeviceDTO {
+ id: string
+ description: string
+ DeviceDTO(device: Device)
}
class DeviceAssembler{
  + domain2DTO(device: Device): DeviceDTO
  }


DeviceRepository "1" -down-> "1" Device: has
DeviceService "1".down.>"1  " DeviceFactory: uses
AddDeviceToRoomController "1".left.>"1" DeviceAssembler: uses
DeviceService "1".down.>"1" DeviceRepository: uses
RoomService "1".right.>"1" RoomRepository: uses
DeviceFactory "1".down.>"1  " Device: creates
AddDeviceToRoomController "1".down.>"1" DeviceService: uses
AddDeviceToRoomController "1".right.>"1" RoomService: uses
DeviceAssembler "1".up.> "*" DeviceDTO: creates
AddDeviceToRoomController "1".down.>"1" RoomAssembler: uses
RoomAssembler "1".down.>"*" RoomDTO: creates


@enduml