//House rest controller

POST http://localhost:8080/houses
Content-Type: application/json

{
  "street": "123 Smart St",
  "doorNumber": "101",
  "postalCode": "90210",
  "countryCode": "US",
  "latitude": 34.0522,
  "longitude": -118.2437
}

###
//Room rest controller

//Add rooms to the house
POST http://localhost:8080/rooms
Content-Type: application/json

{
  "name": "Kitchen",
  "floor": "1",
  "width": 2,
  "length": 4,
  "height": 5
}

###
POST http://localhost:8080/rooms
Content-Type: application/json

{
  "name": "Living Room",
  "floor": "1",
  "width": 3,
  "length": 5,
  "height": 5
}

###
//Get all rooms
GET http://localhost:8080/rooms

###
//Get room by id
GET http://localhost:8080/rooms/db521789-da9d-4736-a7b5-e7a274e00eb5

###

