//Get all sensor types
GET http://localhost:8080/sensor-types

###
//Get all sensor models by sensor type
GET http://localhost:8080/sensor-model?sensorTypeID=Temperature

###
//Get all actuator types
GET http://localhost:8080/actuator-types/

###
//Get all actuator models by actuator type
GET http://localhost:8080/actuator-model/BlindRoller

###
//Get all supported units
GET http://localhost:8080/units

###

//Create a new sensor type
POST http://localhost:8080/sensor-types
Content-Type: application/json

{
  "description": "Temperature sensor",
  "unitID": "Celsius"
}