GET http://localhost:8080/actuator-models?actuatorTypeID=BlindRoller
Content-Type: application/json

> {%
    client.global.set("actuatorModelPath", response.body._embedded.actuatorModelDTOList[0].actuatorModelPath);
%}


###

POST http://localhost:8080/actuators
Content-Type: application/json

{
  "type": "genericActuator",
  "deviceID": "{{blindsDeviceId}}",
  "actuatorModelPath": "{{actuatorModelPath}}",
  "actuatorName": "GTX2000",
  "actuatorTypeID": "BlindRoller"
}

> {%
    client.global.set("blindRollerActuatorID", response.body.id);
%}