POST http://localhost:8080/actuators/set-blindRoller
Content-Type: application/json

{
  "type": "valueDTO",
  "deviceID": "demoDevice4",
  "actuatorID": "actuator1",
  "value": 90
}

### Get the position of the blind roller
GET http://localhost:8080/logs/get-position-blindRoller?deviceID=demoDevice4