@startuml

package "Backend" {

    Component Infrastructure {
        package Tests {
        }
        package Persistence {
        }
    }

    Component "Interface Adapters" {
        package Controllers {
        }
        package Repositories {
        }
    }

    Component "Services Layer" {
        package "Services" {
        }

    }

    Component "Entities/Core/Domain" {
        package Aggregates {
        }
        package "Value Objects" {
        }
        package "IServices" {
        }
        package "IRepositories"{
                }

    }

    ' Dependencies
    Infrastructure.Tests ..> "Interface Adapters.Controllers" : .
    Infrastructure.Persistence <.. "Interface Adapters.Repositories" : .
    "Interface Adapters.Controllers" ..> "Services" : .
    "Services" ..> Aggregates : .
    "Services" ..> "Value Objects" : .
    "Interface Adapters.Repositories" ..> Services
    "Repositories" ..|> "IRepositories" : .
    "Services" ..|> "IServices" : .
}

@enduml
