@startuml
!pragma layout smetana
participant "Something" as Client
participant "Controller" as Controller
participant "RoomService" as RoomService
participant "RoomRepository" as RoomRepo
participant "RoomAssembler" as RoomAssembler
participant "Device" as Device
participant "ActuatorFactory" as ActuatorFactory
participant "ActuatorCatalogue" as ActuatorCatalogue
participant "DeviceRepository" as DeviceRepo

Client -> Controller : getRooms()
activate Controller
Controller -> RoomService : getRooms()
activate RoomService
RoomService -> RoomRepo : findAllRooms()
activate RoomRepo
RoomRepo --> RoomService : roomsList
deactivate RoomRepo
RoomService --> Controller : roomsList
deactivate RoomService
Controller -> RoomAssembler : toDTO(roomsList)
activate RoomAssembler
RoomAssembler --> Controller : roomsDTOList
deactivate RoomAssembler
Controller --> Client : roomsDTOList
deactivate Controller

Client -> Controller : getDevicesInRoom(roomName)
activate Controller
Controller -> RoomService : getDevicesInRoom(roomName)
activate RoomService
RoomService -> DeviceRepo : findDevicesInRoom(roomName)
activate DeviceRepo
DeviceRepo --> RoomService : devicesList
deactivate DeviceRepo
RoomService --> Controller : devicesList
deactivate RoomService
Controller -> RoomAssembler : toDTO(devicesList)
activate RoomAssembler
RoomAssembler --> Controller : devicesDTOList
deactivate RoomAssembler
Controller --> Client : devicesDTOList
deactivate Controller

Client -> Controller : addActuatorToDevice(deviceId, actuatorType)
activate Controller
Controller -> ActuatorFactory : createActuator(actuatorType)
activate ActuatorFactory
ActuatorFactory -> ActuatorCatalogue : validateActuatorType(actuatorType)
activate ActuatorCatalogue
ActuatorCatalogue --> ActuatorFactory : isValid
deactivate ActuatorCatalogue
ActuatorFactory --> Controller : actuator
deactivate ActuatorFactory

Controller -> Device : addActuator(actuator)
activate Device
Device -> DeviceRepo : saveUpdatedDevice()
activate DeviceRepo
DeviceRepo --> Device : success
deactivate DeviceRepo
Device --> Controller : success
deactivate Device
Controller --> Client : success
deactivate Controller
@enduml
